language: node_js
node_js:
  - "9"
sudo: false

branches:
  only:
  - master

install:
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: oNahH6vxdULgXjPEXV0jUPb1ZXGUh1AUn8GefnZC1xEDzlp55ccr85wiw7yZDlL69l7dVwjiA4Z9yDH8tdeTqZpZIcheFO+KPPzp/ZeekN5K++z74+tGaaOrokkH/LxrGSdql+DSZRB63MFWZCIXIXtjVRr/H6kRovyb/CqhP0ztU3szsIwlIk07UA6eU/HkFajPUunZPlzrMIfau+z5moR2Sm7QGzXYztowyXTTC8Rp29LKwaKqA7oX6UhFyBBv0aAK6IkpnWuGQJzhh/rqvDdrU46ZFhev9SGneD7nr+g+a14vVlymjzOyCDgtwv+QeSaAiDkmMgPF/dF8ggesYbjVBazEKTlE3JFMeWqBJbiN5W4NF1HaNB97yRqMGc75fMj0plqsJJJLqm1+GGb+ZwKf4B9tCPtMgH6IE3UzZrRcn/YtQ/3g1qLzZdAzAZQ6X/+YAyO+Chr3BCnquqJOe0AOIh9qvbFuqTPmuEZFv8blgxHIobuZLGwvXLQw8vvTvtk0g6Sxme6YTFl+kvH+gvZmuGMS/KI62a9Te44LuoKC2mh9P7LKwxFqpyaRIFzDW981H694MW0ou1PPJYz/y3oMBCBuFIkfjPIrcU27293mUSRsQCJWkp1uhYk9vJQIAG9wbEHHarjtvMNBbvzy5RNqYGjrlrCCjterUvGT6Vw=
  app: course-player-react