language: node_js
node_js:
  - "9"
sudo: false

branches:
  only:
  - master

install:
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: RZWp4jUGeqHEThl9dEGJITA/gpKPKP/P+OWTpwNGXKXT2oSd7OtIA528fwrYhg930QySnlnvvCRi8gFXWydjnLgIUxSm7MLENd82av9suOq0bxJnvAXOrFZlAe9XKnnoYwPuYemgb/1LBKEwOllv/CbWOdMbUxRPjhuBOHmsCKKj6tl/yCFWcR2RO7F+VGG3FzxxyN86HPwZNrfdUkVifLOZjzedsQkk8uVhBvhpf85iuV80bU0oPCAAil1AZb7n6QdnfyvCK0bYlPKp5w24m1/+9KVVvoqYfmrIiAKLgkgLdM/KBpX0yaIegbfyjUvWyRYJokqVfL87lbt7nt3VV84fjlmRYn8hLQ4N/yxmZwv1uPZEibIHrdbncwir7tKuaRAoAc3ZJ5eqKGoBBoQQFvlBevzjbbh1LZZz3UR5nLRqx4Dj0XWcpNSsXMx/2jrN9anN37LCUKf6pc0Fn58eY0Lai2L6zNhY1vQOyM8Xp8BZk1BRHZJKFLGgSqC4YEPTmQMGrf2NHkFkrUG9l7H8EEMYkHV8omQnD2HJzEzPPksa2/C1DhSgVKJDXmqsGz5IS9qxh9AeWvtiznIIm5SCC3sp7oimgI0/sSuFY4j8ELSfH0TTtqB1EvLiWuyBfwdERKe8XjXi0uVkjiwYHkbtURCxzFEqzvaumSayiMmdi4I=
  app: course-player-react