language: node_js
node_js:
  - "9"
sudo: false

branches:
  only:
  - master

install:
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: YMOQrfNwgHe5wv8hS+0KfayM78ectciYvmgZ+hSLjhzY8CSdzR6ueQTqj7HEbCNSEt/A8tFAAlvrNb3wh0/SexiNevw7LUryFRMTwfdb8tJnc7+9HLAdiN8LjYOQ+6niswXk9sr9qwqFVPA5LDs6BvE/T2oMCCgJpoIwU1lEHoZsgwPNCc/qYDqAVXvl91BfRojYqAuJ5hcyeBUbIVAmG34oLcFY4cIQ3kZE3bGFct6L7448Gn3NOleoBgvmicYsierYyPwz9LxWSzILOaRKoftEvtNexJlw3wEUgtnfwYBXyGaMEV5Tz6OlWFuTaz6QdT6jpfipgtKT6PDDoJXSkM1WOsOEfbWQ4unHB5TDdYfNzEosC5yRlJ1yiGUswVy7wv6OzRmDeIiWn/oOUOvnamZVxz7l+lcgDwkx6yCtVRnHPGCcY78kL6prfFjnTf3GiitirqYvxHl7jXhd3VhZ98dHbbzbSKZAgdUgsmdnlVHQwLg7xwpa6wQIDfJEnW13xFTKsjEtOnVH9fQujfc4YB/AdBbWzfD5rFNDSDWatxzC8JtLxwGpVBKBlFjAa3lEp32EQx3vmHJpxW5EGDmlKQt8EvNmC50CHECIkLRIE1nzONP+a0G7zi9y0OcROfPmR5MHE710suApK3mpEJ7F5YJH/oXUDl9ijAwfh/ABa7Y=
  app: course-player-react